// Generated by LiveScript 1.4.0
(function(){
  import$(this, require('prelude-ls'));
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
